### ISSUE TITLE
zipping bayesian models and providing readme...

### ISSUE THREAD

**Issue by ryanpeek** [Delta-Stewardship-Council/swg-21-connectivity#158]
@layamane I think we can save some space and still retain all the iterations. What would be great is a `README.txt` file in the `bayes_models` directory. 

Ideally we can zip up all or chunks of these models (i.e., mod01-10.zip would contain all those models). That would help compress some of the larger pieces, and also save space/time for folks cloning/pushing/pulling the repo.

The README could have basically two columns: the dir name (mod01) and a super short summary of the model iteration (i.e., jags lagged chl vs. multiple covariates). Would just help orient folks to what is what. I think you may already have a spreadsheet of this...so if you have csv we can drop that in here instead of a README. If the differences are super nuanced, I'd just duplicate the summary and add "minor iteration" or something like that. Keep it simple...and hopefully this isn't a big ask!! If so, let me know and I can try to help pull it together.

**Comment by ryanpeek** [comment]
Hi @layamane sorry was in the field most of last week so couldn't circle back to this. I'd say if we don't mind not including the raw models, I can put those in a .gitignore in that folder, and then just keep it as is. I'd forgotten about your Rmd, I think that's fine, we may want to add a README in the folder that points folks to that Rmd so that it's clear where everything is and what it is. I meant zipping models 1 through 10 together to keep the file sizes reasonable, `github` doesn't like files over 50MB, and won't push files over 100MB, so if we can zip things up a bit it can help. I can take a crack at it if you'd like and you can review the pull request if you want...the good news is we'll have a version of whats there no matter what.

**Comment by layamane** [comment]
Very good, thanks for helping with this process @ryanpeek.  Yay being in the field!  I'm totally fine with you zipping things and putting the raw models in .gitignore.  I'll just plan on keeping separate raw files on my local machine.  Attached is an example README.txt.  Feel free to change as desired.  Note also that scripts/functions/f_make_bayes_mod1 - mod19 are needed to run the models but should probably be zipped in the bayes_models folder?  Although the file paths will no longer work to call those functions within individual bayes models.  
[README.txt](https://github.com/Delta-Stewardship-Council/swg-21-connectivity/files/11561171/README.txt)
