### ISSUE TITLE
delete `data` folder...

### ISSUE THREAD

**Issue by ryanpeek** [Delta-Stewardship-Council/swg-21-connectivity#159]
Hey all, same request...these data are in our commit history and can be retrieved...however if they are no longer currently used, we should delete from the main branch. Please take a look and let me know if there's anything you see that we need, and any specific locations that pull these data in (script names).

Thanks! 👍

**Comment by ryanpeek** [comment]
@goertler @layamane @catarfish @shrkhanna 
Just double checking...nothing currently uses the original "`data`" folder correct? I haven't seen anything yet, and again, we can always revert if necessary.

**Comment by layamane** [comment]
I don't see anything that I need.  Thanks @ryanpeek!
