### ISSUE TITLE
suggest renaming `data_model` to `model_gam`

### ISSUE THREAD

**Issue by ryanpeek** [Delta-Stewardship-Council/swg-21-connectivity#161]
@shrkhanna @goertler 
To match the other model folder, I'm suggesting renaming the `data_model` folder to `model_gam` and the `bayes_models` folder to `model_bayes` for consistency. 

I would also recommend deleting the `Archive` folder in the `data_model` folder unless there are active scripts that need the data inside it, at which point we shouldn't have anything in there anyway. Since these data are committed and already in git, we can always go back to retrieve them should there be a need, but better to show a clean version of what the final working version of things is.

I can make a pull request with these changes.

**Comment by catarfish** [comment]
Hi @ryanpeek this sounds okay to me. I don't remember why we have archived scripts in there so we probably don't need them :)
I'll let @shrkhanna speak up if she thinks otherwise.

**Comment by shrkhanna** [comment]
I think I'm good too. Go ahead Ryan. You can delete them.

Shruti

**Comment by ryanpeek** [comment]
Thanks all! will do. 👍
